#ローカル開発用DBの定義

version: '3'
services:
  postgres:
    image: postgres:10-alpine
    # 任意のパスワード
    environment:
      POSTGRES_PASSWORD: password
    # ホスト側は任意のディレクトリ
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    # ホスト側は任意のポート
    ports:
      - 5000:5432